#!/bin/bash

PREFIX=".config_"
CFGLINK=".config"

print_usage() {
	echo "Usage: `basename $0` CONFIG_NAME"
}

if test $# -ne 1; then
	echo "Invalid number of parameters"
	print_usage
	exit 1
fi

CFGFILE="${PREFIX}$1"

if test -f $CFGFILE; then
	rm -f $CFGLINK
	ln -s $CFGFILE $CFGLINK
else
	echo "File '$CFGFILE' doesn't exist"
	exit 1
fi
